#!/bin/bash

host=$1
default_prefix="10.0"
[ -z "$host" ] && echo "ERROR: please give me a host to login." && exit 1

if [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    host=${default_prefix}.${host}
elif [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    a=`echo $host | awk -F'.' '{print $1}'`
    if [ "$a" == "16" -o "$a" == "17" ] ;then
        host="172."$host
    else 
        host="10."$host
    fi 
else
    host=`cat ~/.my_hosts | grep $host | head -1 | awk '{print $2}'`
    pass=`cat ~/.my_hosts | grep $host | head -1 | awk '{print $3}'`
    [ -z "$host" ] && echo "ERROR: host alist '$host' not found in ~/.my_hosts" && exit 1
    if [ -n "$pass" ]; then
        echo "===> Using password to login to host: ${host}"
        echo "===> cmd tool 'expect' is not usable. You need to type in password by your self."
        echo "===>  pswd: ${pass}"
        ssh root@${host}  
        exit 0
    fi
fi

echo "===> Using key to login to host: ${host}"
ssh root@${host}
