#!/bin/bash

host=$1
default_prefix="192.168"
[ -z "$host" ] && echo "ERROR: please give me a host to login." && exit 1

if [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    host=${default_prefix}.${host}
elif [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    a=`echo $host | awk -F'.' '{print $1}'`
    if [ "$a" == "16" ]; then
        host="172."$host
    else
        host="192."$host
    fi
elif [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    host=$host
else
    host=`cat ~/.my_hosts | grep $host | head -1 | awk '{print $2}'`
    pass=`cat ~/.my_hosts | grep $host | head -1 | awk '{print $3}'`
    [ -z "$host" ] && echo "ERROR: host alist '$host' not found in ~/.my_hosts" && exit 1
    if [ -n "$pass" ]; then
        if [ -f '/usr/bin/expect' ]; then
            /Users/leialan/my_github/shell_tools/s/expect_login $host 22 $pass
            exit 0
        else
            echo "===> Using password to login to host: ${host}"
            echo "===> cmd tool 'expect' is not usable. You need to type in password by your self."
            echo "===>  pswd: ${pass}"
            ssh root@${host}
            exit 0
        fi
    fi
fi

echo "===> Using key to login to host: ${host}"
if [ -z "$2" ]; then
    ssh root@${host} -p 22
else
    ssh root@${host} -p $2
fi
